name: Sauce demo web-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          command: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: results.json
          path: ./testrail/results.json
  testrail_run:
    needs: cypress-run
    runs-on: ubuntu-latest
    env:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download Results
        uses: actions/download-artifact@master
        with:
          name: results.json
          path: ./testrail
      - run: cat ./testrail/results.json
      - shell: pwsh
        run: |
          chmod +x ./testrail/create_testplan.sh
          sh ./testrail/create_testplan.sh
          ls -a
      - shell: pwsh
        run: |
          chmod +x ./testrail/post_results.sh
          sh ./testrail/post_results.sh
          ls -a
